// Generated by https://quicktype.io

export interface PlacesResponse {
    type:        string;
    query:       string[];
    features:    Feature[];
    attribution: string;
}

export interface Feature {
    id:            string;
    type:          string;
    place_type:    string[];
    relevance:     number;
    properties:    Properties;
    text_es:       string;
    place_name_es: string;
    text:          string;
    place_name:    string;
    center:        number[];
    geometry:      Geometry;
    context:       Context[];
    bbox?:         number[];
}

export interface Context {
    id:           string;
    text_es:      string;
    text:         string;
    short_code?:  ShortCode;
    wikidata?:    Wikidata;
    language_es?: Language;
    language?:    Language;
}

export enum Language {
    Es = "es",
}

export enum ShortCode {
    Co = "co",
    CoCun = "CO-CUN",
    CoDc = "CO-DC",
}

export enum Wikidata {
    Q232564 = "Q232564",
    Q2841 = "Q2841",
    Q739 = "Q739",
}

export interface Geometry {
    coordinates: number[];
    type:        string;
}

export interface Properties {
    foursquare?: string;
    landmark?:   boolean;
    category?:   string;
    address?:    string;
}
